# Global options
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
namespace: monitoring

# Generate a ConfigMap for each dashboard
configMapGenerator:

#################################################
# Views Dashboards
#################################################

- name: dashboards-k8s-views-global
  files: [ dashboards/k8s-views-global.json ]

- name: dashboards-k8s-views-namespaces
  files: [ dashboards/k8s-views-namespaces.json ]

- name: dashboards-k8s-views-nodes
  files: [ dashboards/k8s-views-nodes.json ]

- name: dashboards-k8s-views-pods
  files: [ dashboards/k8s-views-pods.json ]

#################################################
# System / Addons Dashboards
#################################################

- name: dashboards-k8s-system-api-server
  files: [ dashboards/k8s-system-api-server.json ]

- name: dashboards-k8s-system-coredns
  files: [ dashboards/k8s-system-coredns.json ]

- name: dashboards-k8s-addons-prometheus
  files: [ dashboards/k8s-addons-prometheus.json ]

- name: app-monitoring-staging
  files: [ dashboards/app_monitoring_staging.json ]

- name: github
  files: [ dashboards/github-dashboard.json ]

- name: dashboards-postgresql-db-staging
  files: [ dashboards/postgresql-db-staging.json ]
